/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerInfo {
  'country' : string,
  'name' : string,
  'address' : string,
  'phone' : string,
}
export interface Order {
  'id' : bigint,
  'customerInfo' : CustomerInfo,
  'status' : OrderStatus,
  'total' : number,
  'timestamp' : Time,
  'items' : Array<[bigint, bigint]>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'addProduct' : ActorMethod<[string, string, number, string, string], bigint>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'cancelOrder' : ActorMethod<[bigint], boolean>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'placeOrder' : ActorMethod<[string, string, string, string], [] | [bigint]>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], boolean>,
  'updateProductPrice' : ActorMethod<[bigint, number], boolean>,
  'updateProductStock' : ActorMethod<[bigint, boolean], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];